# Tugas 1

In [ ]:
import pandas as pd
import numpy as np
import math

In [ ]:
dataset_url="https://raw.githubusercontent.com/HambaliFitrianto/datamining/main/data-kejadian-bencana-banjir-di-provinsi-dki-jakarta-tahun-2017-bulan-desember.csv"
p=pd.read_csv(dataset_url, index_col=0)

In [ ]:
p

,kecamatan,kelurahan,rw,jumlah_terdampak_rw,jumlah_terdampak_rt,jumlah_terdampak_kk,jumlah_terdampak_jiwa,ketinggian_air,tanggal_kejadian,lama_genangan,jumlah_meninggal,jumlah_hilang,jumlah_luka_berat,jumlah_luka_ringan,jumlah_pengungsi_tertinggi,jumlah_tempat_pengungsian,nilai_kerugian
kota_administrasi,,,,,,,,,,,,,,,,,
Jakarta Barat,KALIDERES,KAMAL,"01, 04",2,6,0,0,20 s/d 30 cm,"tgl. 03, 04, 06, 20",0,0,0,0,0,0,0,0
Jakarta Barat,GROGOL PETAMBURAN,JELAMBAR BARU,"01,06, 07",3,2,0,0,10 s/d 20 cm,"tgl. 05, 06, 07, 09",0,0,0,0,0,0,0,0
Jakarta Selatan,PASAR MINGGU,JATI PADANG,6,1,1,8,35,5 - 50 cm,"tgl. 01, 11, 16, 20",0,0,0,0,35,1,0,0
Jakarta Selatan,PANCORAN,KALIBATA,"05, 09, 10",3,3,0,0,20 s/d 30 cm,tgl. 12,0,0,0,0,0,0,0,0
Jakarta Selatan,SETIABUDI,KUNINGAN TIMUR,5,1,1,0,0,20 s/d 25 cm,tgl. 12,0,0,0,0,0,0,0,0
Jakarta Selatan,TEBET,KEBON BARU,6,1,1,0,0,40 cm,tgl. 12,0,0,0,0,0,0,0,0
Jakarta Selatan,TEBET,BUKIT DURI,"04, 06, 08",3,3,0,0,20 s/d 30 cm,tgl. 12,0,0,0,0,0,0,0,0
Jakarta Selatan,TEBET,MANGGARAI,3,1,1,0,0,20 cm,tgl. 12,0,0,0,0,0,0,0,0
Jakarta Selatan,JAGAKARSA,JAGAKARSA,3,1,1,0,0,10 s/d 20 cm,tgl. 16,0,0,0,0,0,0,0,0
Jakarta Selatan,CILANDAK,PONDOK LABU,1,1,1,0,0,50 s/d 70 cm,tgl. 20,0,0,0,0,0,0,0,0
Jakarta Timur,MAKASAR,CIPINANG MELAYU,"RW. 03, 04",2,11,0,0,20 s/d 50 cm,"tgl. 11, 16, 17, 20",0,0,0,0,0,0,0,0
Jakarta Timur,JATINEGARA,CIPINANG MUARA,13,1,3,0,0,20 s/d 40 cm,tgl. 11,0,0,0,0,0,0,0,0
Jakarta Timur,CAKUNG,RAWA TERATE,5,1,1,0,0,20 s/d 40 cm,tgl. 11,0,0,0,0,0,0,0,0
Jakarta Timur,PASAR REBO,KALISARI,"03, 11",2,2,0,0,20 s/d 40 cm,tgl. 11,0,0,0,0,0,0,0,0
Jakarta Timur,KRAMAT JATI,CILILITAN,1,1,1,0,0,10 s/d 50 cm,tgl. 12,0,0,0,0,0,0,0,0
Jakarta Utara,PENJARINGAN,KAPUK MUARA,"01,",1,4,0,0,5 s/d 15 cm,"tgl. 03, 06",0,0,0,0,0,0,0,0
Jakarta Utara,PENJARINGAN,KAMAL MUARA,"01, 04,",2,2,0,0,10 s/d 50 cm,"tgl. 03, 04, 05, 06, 07, 08",0,0,0,0,0,0,0,0
Jakarta Utara,PENJARINGAN,PENJARINGAN,"01, 02, 03, 17",4,4,0,0,5 s/d 30 cm,"tgl. 03, 05, 06",0,0,0,0,0,0,0,0
Jakarta Utara,PENJARINGAN,PLUIT,"01, 11, 20, 22",4,4,0,0,10 s/d 30 cm,"tgl. 04, 05, 06",0,0,0,0,0,0,0,0
Jakarta Utara,PENJARINGAN,PEJAGALAN,016,1,1,0,0,10 s/d 20 cm,tgl 05,0,0,0,0,0,0,0,0
Jakarta Utara,CILINCING,MARUNDA,"01, 02, 04 ,06, 07, 09",6,6,123,369,5 s/d 30 cm,"tgl. 04, 05, 06",0,0,0,0,0,0,0,0
Jakarta Utara,CILINCING,CILINCING,"06, 09",2,2,0,0,5 s/d 15 cm,tgl. 05,0,0,0,0,0,0,0,0
Jakarta Utara,PADEMANGAN,ANCOL,10,1,1,0,0,10 s/d 15 cm,tgl. 05,0,0,0,0,0,0,0,0
Jakarta Utara,TANJUNG PRIOK,SUNTER AGUNG,"03, 06, 08",3,3,0,0,05 s/d 15 cm,"tgl. 05, 06, 07",0,0,0,0,0,0,0,0
Jakarta Utara,KOJA,KOJA,11,1,1,0,0,10 s/d 15 cm,tgl. 05,0,0,0,0,0,0,0,0
Kepulauan Seribu,KEPULAUAN SERIBU SELATAN,PULAU TIDUNG,"02, 03",2,5,0,0,10 s/d 20 cm,tgl. 05,0,0,0,0,0,0,0,0

In [ ]:
def diss(x,y):
  a = 4
  b = 0
  for col in ["kecamatan", "kelurahan", "rw", "jumlah_terdampak_rw", "jumlah_terdampak_rt",	"jumlah_terdampak_kk", "jumlah_terdampak_jiwa",	"ketinggian_air",	"tanggal_kejadian",	"lama_genangan",	"jumlah_meninggal", "jumlah_hilang",	"jumlah_luka_berat",	"jumlah_luka_ringan",	"jumlah_pengungsi_tertinggi",	"jumlah_tempat_pengungsian",	"nilai_kerugian", "kota_administrasi"	]:
    if p[col][x] == p[col][y]:
      b+=1
    return (a-b)/a

In [ ]:
print(diss(1,1))

0.75

In [ ]:
p.describe()

,jumlah_terdampak_rw,jumlah_terdampak_rt,jumlah_terdampak_kk,jumlah_terdampak_jiwa,lama_genangan,jumlah_meninggal,jumlah_hilang,jumlah_luka_berat,jumlah_luka_ringan,jumlah_pengungsi_tertinggi,jumlah_tempat_pengungsian,nilai_kerugian
count,26.000000,26.000000,26.000000,26.000000,26.0,26.0,26.0,26.0,26.000000,26.000000,26.0,26.0
mean,1.961538,2.730769,5.038462,15.538462,0.0,0.0,0.0,0.0,1.346154,0.038462,0.0,0.0
std,1.280024,2.324783,24.110547,72.417805,0.0,0.0,0.0,0.0,6.864065,0.196116,0.0,0.0
min,1.000000,1.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
25%,1.000000,1.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
50%,1.500000,2.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
75%,2.750000,3.750000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.0
max,6.000000,11.000000,123.000000,369.000000,0.0,0.0,0.0,0.0,35.000000,1.000000,0.0,0.0

In [ ]:
#normalisasi jumlah_terdampak_rw
std_jtw = 1.280024
mean_jtw = 1.961538
for col1 in ["jumlah_terdampak_rw"]:
    p1 = p[col1]
    hasil1 = (p1-mean_jtw)/std_jtw
    print(hasil1)

#normalisasi jumlah_terdampak_rt
std_jtr = 2.324783	
mean_jtr = 3.366667
for col2 in ["jumlah_terdampak_rt"]:
    p2 = p[col2]
    hasil2 = (p2-mean_jtr)/std_jtr
    print(hasil2)

kota_administrasi
Jakarta Barat       0.030048
Jakarta Barat       0.811283
Jakarta Selatan    -0.751187
Jakarta Selatan     0.811283
Jakarta Selatan    -0.751187
Jakarta Selatan    -0.751187
Jakarta Selatan     0.811283
Jakarta Selatan    -0.751187
Jakarta Selatan    -0.751187
Jakarta Selatan    -0.751187
Jakarta Timur       0.030048
Jakarta Timur      -0.751187
Jakarta Timur      -0.751187
Jakarta Timur       0.030048
Jakarta Timur      -0.751187
Jakarta Utara      -0.751187
Jakarta Utara       0.030048
Jakarta Utara       1.592519
Jakarta Utara       1.592519
Jakarta Utara      -0.751187
Jakarta Utara       3.154989
Jakarta Utara       0.030048
Jakarta Utara      -0.751187
Jakarta Utara       0.811283
Jakarta Utara      -0.751187
Kepulauan Seribu    0.030048
Name: jumlah_terdampak_rw, dtype: float64
kota_administrasi
Jakarta Barat       1.132722
Jakarta Barat      -0.587869
Jakarta Selatan    -1.018016
Jakarta Selatan    -0.157721
Jakarta Selatan    -1.018016
Jakarta Selatan    -1.018016
Jakarta Selatan    -0.157721
Jakarta Selatan    -1.018016
Jakarta Selatan    -1.018016
Jakarta Selatan    -1.018016
Jakarta Timur       3.283460
Jakarta Timur      -0.157721
Jakarta Timur      -1.018016
Jakarta Timur      -0.587869
Jakarta Timur      -1.018016
Jakarta Utara       0.272427
Jakarta Utara      -0.587869
Jakarta Utara       0.272427
Jakarta Utara       0.272427
Jakarta Utara      -1.018016
Jakarta Utara       1.132722
Jakarta Utara      -0.587869
Jakarta Utara      -1.018016
Jakarta Utara      -0.157721
Jakarta Utara      -1.018016
Kepulauan Seribu    0.702574
Name: jumlah_terdampak_rt, dtype: float64

In [ ]:
# Menghitung jarak data Numeric dengan cara Euclidean
def num_p(a,b,c):
    result = 0
    for col in [hasil1, hasil2]:
        result = math.pow(abs(col[a] - col[b]), c)
    return result**(1/c)

In [ ]:
print(num_p(1,2,2))
print(num_p(1,3,2))
print(num_p(1,4,2))

0.4301476739979603
0.4301476739979603
0.4301476739979603

**Similarity**

In [ ]:
print("Jarak d(1,2) =", diss(1,2)+num_p(1,2,2))

Jarak d(1,2) = 1.4301476739979604

In [ ]:
print("Jarak d(1,2) =", diss(1,3)+num_p(1,3,3))

Jarak d(1,2) = 1.4301476739979604

In [ ]:
print("Jarak d(1,2) =", diss(1,4)+num_p(1,4,4))

Jarak d(1,2) = 1.4301476739979604

# Tugas 2 : Diskritisasi

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dataset_url="https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv"
data=pd.read_csv(dataset_url)

In [ ]:
data[['sepal_length']]

     sepal_length
0             5.1
1             4.9
2             4.7
3             4.6
4             5.0
..            ...
145           6.7
146           6.3
147           6.5
148           6.2
149           5.9

[150 rows x 1 columns]

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')

In [ ]:
data['sepal_length']=est.fit_transform(data[['sepal_length']])

In [ ]:
data['sepal_length']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
145    2.0
146    2.0
147    2.0
148    2.0
149    1.0
Name: sepal_length, Length: 150, dtype: float64

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')
data['sepal_width']=est.fit_transform(data[['sepal_width']])

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')
data['petal_length']=est.fit_transform(data[['petal_length']])

In [ ]:
data['petal_length']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
145    2.0
146    2.0
147    2.0
148    2.0
149    2.0
Name: petal_length, Length: 150, dtype: float64

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')
data['petal_width']=est.fit_transform(data[['petal_width']])

In [ ]:
data['petal_width']

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
145    3.0
146    3.0
147    3.0
148    3.0
149    2.0
Name: petal_width, Length: 150, dtype: float64

# Tugas 3 : Knn

In [ ]:
# Data in a csv format, each observation has a 4 measurements/features 
# and the species type.
from IPython.display import IFrame
IFrame('http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', width=400, height=200)

In [ ]:
#Import the load_iris function from datsets module
from sklearn.datasets import load_iris

In [ ]:
#Create bunch object containing iris dataset and its attributes.
iris = load_iris()

In [ ]:
type(iris)

sklearn.utils.Bunch

In [ ]:
#Print the iris data
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [ ]:
#Names of 4 features (column names)
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

In [ ]:
#Integers representing the species: 0 = setosa, 1=versicolor, 2=virginica
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]

In [ ]:
# 3 classes of target
print(iris.target_names)

['setosa' 'versicolor' 'virginica']

In [ ]:
print(type(iris.data))
print(type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [ ]:
# we have a total of 150 observations and 4 features
print(iris.data.shape)

(150, 4)

In [ ]:
# Feature matrix in a object named X
X = iris.data
# response vector in a object named y
y = iris.target

In [ ]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)

Train the Model

In [ ]:
# splitting the data into training and test sets (80:20)
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=4)

In [ ]:
#shape of train and test objects
print(X_train.shape)
print(X_test.shape)

In [ ]:
# shape of new y objects
print(y_train.shape)
print(y_test.shape)

In [ ]:
#import the KNeighborsClassifier class from sklearn
from sklearn.neighbors import KNeighborsClassifier

#import metrics model to check the accuracy 
from sklearn import metrics
#Try running from k=1 through 25 and record testing accuracy
k_range = range(1,26)
scores = {}
scores_list = []
for k in k_range:
        knn = KNeighborsClassifier(n_neighbors=k)
        knn.fit(X_train,y_train)
        y_pred=knn.predict(X_test)
        scores[k] = metrics.accuracy_score(y_test,y_pred)
        scores_list.append(metrics.accuracy_score(y_test,y_pred))

In [ ]:
#Testing accuracy for each value of K
scores

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

#plot the relationship between K and the testing accuracy
plt.plot(k_range,scores_list)
plt.xlabel('Value of K for KNN')
plt.ylabel('Testing Accuracy')

K values with 3 to 19 has the same accuracy which is 96.66, so we can use any one value from that, i choose K as 5 and train the model with full training data

In [ ]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X,y)

In [ ]:
#0 = setosa, 1=versicolor, 2=virginica
classes = {0:'setosa',1:'versicolor',2:'virginica'}

#Making prediction on some unseen data 
#predict for the below two random observations
x_new = [[3,4,5,2],
         [5,4,2,2]]
y_predict = knn.predict(x_new)

print(classes[y_predict[0]])
print(classes[y_predict[1]])

# Tugas 4 : Naive Bayes Classifer

In [ ]:
# Naive Bayes Classification

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import pandas as pd

In [ ]:
# Importing the dataset
dataset = pd.read_csv('iris.csv')

In [ ]:
#looking at the first 5 values of the dataset
dataset.head()

In [ ]:
%matplotlib inline
img=mpimg.imread('iris_types.jpg')
plt.figure(figsize=(20,40))
plt.axis('off')
plt.imshow(img)

In [ ]:
#Spliting the dataset in independent and dependent variables
X = dataset.iloc[:,:4].values
y = dataset['species'].values

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 82)

In [ ]:
# Feature Scaling to bring the variable in a single scale
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
# Fitting Naive Bayes Classification to the Training set with linear kernel
from sklearn.naive_bayes import GaussianNB
nvclassifier = GaussianNB()
nvclassifier.fit(X_train, y_train)

In [ ]:
# Predicting the Test set results
y_pred = nvclassifier.predict(X_test)
print(y_pred)

In [ ]:
#lets see the actual and predicted value side by side
y_compare = np.vstack((y_test,y_pred)).T
#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare[:5,:]

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

In [ ]:
#finding accuracy from the confusion matrix.
a = cm.shape
corrPred = 0
falsePred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrPred +=cm[row,c]
        else:
            falsePred += cm[row,c]
print('Correct predictions: ', corrPred)
print('False predictions', falsePred)
print ('\n\nAccuracy of the Naive Bayes Clasification is: ', corrPred/(cm.sum()))

# Tugas 5 : K-Means